/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tads4.sistemasroupas.views;

import com.tads4.sistemasroupas.control.FuncionarioController;
import com.tads4.sistemasroupas.model.Funcionario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author GiovanePerlin
 */
public class FormListarFuncionarios extends javax.swing.JFrame {

    private FuncionarioController controller = new FuncionarioController();

    /**
     * Creates new form FormCadastrarFuncionario
     */
    public FormListarFuncionarios() {
        initComponents();
        this.listarFuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanelFuncionarios = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jLabelFuncionarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listar Funcionários");
        setMinimumSize(new java.awt.Dimension(1005, 448));
        setResizable(false);

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "USUÁRIO", "NOME", "CPF", "RG", "SEXO", "FUNÇÃO", "SALÁRIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFuncionarios.setEnabled(false);
        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jScrollPanelFuncionarios.setViewportView(jTableFuncionarios);
        if (jTableFuncionarios.getColumnModel().getColumnCount() > 0) {
            jTableFuncionarios.getColumnModel().getColumn(0).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableFuncionarios.getColumnModel().getColumn(1).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(102);
            jTableFuncionarios.getColumnModel().getColumn(2).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTableFuncionarios.getColumnModel().getColumn(3).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableFuncionarios.getColumnModel().getColumn(4).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableFuncionarios.getColumnModel().getColumn(5).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTableFuncionarios.getColumnModel().getColumn(6).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(6).setPreferredWidth(140);
            jTableFuncionarios.getColumnModel().getColumn(7).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(7).setPreferredWidth(100);
        }
        jTableFuncionarios.getAccessibleContext().setAccessibleName("");

        jLabelFuncionarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFuncionarios.setText("Funcionários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jLabelFuncionarios)
                .addContainerGap(459, Short.MAX_VALUE))
            .addComponent(jScrollPanelFuncionarios)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFuncionarios)
                .addGap(18, 18, 18)
                .addComponent(jScrollPanelFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarFuncionarios() {
        DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "USUÁRIO", "NOME", "CPF", "RG", "SEXO", "FUNÇÃO", "SALÁRIO"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Character.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        Object[] row = {"", "", "", "", "", "", "", ""};

        for (Funcionario funcionario : this.controller.listFuncionario()) {
            row[0] = funcionario.getId();
            row[1] = funcionario.getUsuario();
            row[2] = funcionario.getNome();
            row[3] = funcionario.getCpf();
            row[4] = funcionario.getRg();
            row[5] = funcionario.getSexo();
            row[6] = funcionario.getFuncao();
            row[7] = funcionario.getSalario();

            model.addRow(row);
        }
        this.jTableFuncionarios.setModel(model);

        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(model);
        this.jTableFuncionarios.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(3, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(4, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(6, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(7, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(5, SortOrder.ASCENDING));

        sorter.setSortKeys(sortKeys);

        if (jTableFuncionarios.getColumnModel().getColumnCount() > 0) {
            jTableFuncionarios.getColumnModel().getColumn(0).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableFuncionarios.getColumnModel().getColumn(1).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(102);
            jTableFuncionarios.getColumnModel().getColumn(2).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTableFuncionarios.getColumnModel().getColumn(3).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableFuncionarios.getColumnModel().getColumn(4).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableFuncionarios.getColumnModel().getColumn(5).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTableFuncionarios.getColumnModel().getColumn(6).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(6).setPreferredWidth(140);
            jTableFuncionarios.getColumnModel().getColumn(7).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(7).setPreferredWidth(100);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListarFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFuncionarios;
    private javax.swing.JScrollPane jScrollPanelFuncionarios;
    private javax.swing.JTable jTableFuncionarios;
    // End of variables declaration//GEN-END:variables
}
