/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tads4.sistemasroupas.views;

import com.tads4.sistemasroupas.control.FuncionarioController;
import javax.swing.table.DefaultTableModel;


import com.tads4.sistemasroupas.control.ProdutoController;
import com.tads4.sistemasroupas.model.Produto;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author alison
 */
public class FormListarProdutos extends javax.swing.JFrame {

    private ProdutoController controller = new ProdutoController();

    /**
     * Creates new form FormCadastrarFuncionario
     */
    public FormListarProdutos() {
        initComponents();
        this.listarProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanelClientes = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jLabelProdutos = new javax.swing.JLabel();

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO", "VALOR", "TAMANHO", "COR", "CODIGO_BARRA", "MARCA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.setEnabled(false);
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPanelClientes.setViewportView(jTableProdutos);
        jTableProdutos.getAccessibleContext().setAccessibleParent(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelProdutos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelProdutos.setText("Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabelProdutos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelProdutos)
                .addGap(467, 467, 467))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarProduto() {
        DefaultTableModel model;
        model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "TIPO", "VALOR", "TAMANHO", "COR", "CODIGO_BARRA", "MARCA"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        Object[] row = {"", "", "", "", "", "", ""};

        for (Produto produto : this.controller.listProduto()) {
            row[0] = produto.getId();
            row[1] = produto.getTipo();
            row[2] = produto.getValor();
            row[3] = produto.getTamanho();
            row[4] = produto.getCor();
            row[5] = produto.getCodigoBarra();
            row[6] = produto.getMarca();
            model.addRow(row);
        }
        this.jTableProdutos.setModel(model);
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(model);
        this.jTableProdutos.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
        sortKeys.add(new RowSorter.SortKey(6, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(5, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(4, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(3, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        
        sorter.setSortKeys(sortKeys);

        if (jTableProdutos.getColumnModel().getColumnCount() > 0) {
            jTableProdutos.getColumnModel().getColumn(0).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableProdutos.getColumnModel().getColumn(1).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(332);
            jTableProdutos.getColumnModel().getColumn(2).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTableProdutos.getColumnModel().getColumn(3).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(3).setPreferredWidth(120);
            jTableProdutos.getColumnModel().getColumn(4).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTableProdutos.getColumnModel().getColumn(5).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableProdutos.getColumnModel().getColumn(6).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(6).setPreferredWidth(120);
        }
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelProdutos;
    private javax.swing.JScrollPane jScrollPanelClientes;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables

    private class controller {

        
        
        public controller() {
        }
    }
}
